<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Luau</string>
    <key>scopeName</key>
    <string>source.luau</string>
    <key>fileTypes</key>
    <array>
      <string>luau</string>
      <string>lua</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#shebang</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>shebang</key>
      <dict>
        <key>name</key>
        <string>comment.line.shebang.luau</string>
        <key>match</key>
        <string>\A(#!).*(?=$)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.luau</string>
          </dict>
        </dict>
      </dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-semicolon</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
        </array>
      </dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#var-expr</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-alias-declaration</string>
          </dict>
        </array>
      </dict>
      <key>function-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.function.luau</string>
        <key>begin</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))(?:(local)\s+)?(function\b)(?:(?:\s+|(?&lt;=\*))([_$[:alpha:]][_$[:alnum:]]*))?\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.local.luau</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.function.luau</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.definition.function.luau entity.name.function.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?={{endOfStatement}})|(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-body</string>
          </dict>
        </array>
      </dict>
      <key>function-body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#return-type</string>
          </dict>
        </array>
      </dict>
      <key>type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-primitive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-builtin-literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-tuple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-table</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-name</string>
          </dict>
        </array>
      </dict>
      <key>type-primitive</key>
      <dict>
        <key>name</key>
        <string>support.type.primitive.luau</string>
        <key>match</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))(string|number|boolean|nil|any|never|unknown)(?![_$[:alnum:]])(?:(?=\.\.\.)|(?!\.))</string>
      </dict>
      <key>type-builtin-literals</key>
      <dict>
        <key>name</key>
        <string>support.type.builtin.luau</string>
        <key>match</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))(true|false)(?![_$[:alnum:]])(?:(?=\.\.\.)|(?!\.))</string>
      </dict>
      <key>type-typeof</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;![_$[:alnum:]])(?:(?&lt;=\.\.\.)|(?&lt;!\.))typeof(?![_$[:alnum:]])(?:(?=\.\.\.)|(?!\.))(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.expression.typeof.luau</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>type-operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>[&amp;|\?]</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.luau</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>type-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>([_$[:alpha:]][_$[:alnum:]]*)\s*(?:(\.)|(\?\.(?!\s*[[:digit:]])))\s*(&lt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.module.luau</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.luau</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.optional.luau</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>meta.type.parameters.luau punctuation.definition.typeparameters.begin.luau</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.type.parameters.luau punctuation.definition.typeparameters.end.luau</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.type.parameters.luau</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-arguments-body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>([_$[:alpha:]][_$[:alnum:]]*)\s*(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.luau</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>meta.type.parameters.luau punctuation.definition.typeparameters.begin.luau</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.type.parameters.luau punctuation.definition.typeparameters.end.luau</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>meta.type.parameters.luau</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-arguments-body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>([_$[:alpha:]][_$[:alnum:]]*)\s*(?:(\.)|(\?\.(?!\s*[[:digit:]])))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.module.luau</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.luau</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.optional.luau</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.luau</string>
            <key>match</key>
            <string>[_$[:alpha:]][_$[:alnum:]]*</string>
          </dict>
        </array>
      </dict>
      <key>type-tuple</key>
      <dict>
        <key>name</key>
        <string>meta.type.tuple.luau</string>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.rest.luau</string>
            <key>match</key>
            <string>\.\.\.</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>type-parameters</key>
      <dict>
        <key>name</key>
        <string>meta.type.parameters.luau</string>
        <key>begin</key>
        <string>(&lt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typeparameters.begin.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(&gt;)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typeparameters.end.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.luau</string>
            <key>match</key>
            <string>(=)(?!&gt;)</string>
          </dict>
        </array>
      </dict>
      <key>type-table</key>
      <dict>
        <key>name</key>
        <string>meta.table.type.luau</string>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.table.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.table.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#indexer-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-semicolon</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>indexer-declaration</key>
      <dict>
        <key>name</key>
        <string>meta.indexer.declaration.luau</string>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-annotation</string>
          </dict>
        </array>
      </dict>
      <key>return-type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.return.type.luau</string>
            <key>begin</key>
            <string>(?&lt;=\))\s*(:)(?=\s*\S)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.luau</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;![:|&amp;])(?=$|^|[{};,]|//)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.return.type.luau</string>
            <key>begin</key>
            <string>(?&lt;=\))\s*(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation.luau</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;![:|&amp;])((?=[{};,]|//|^\s*$)|((?&lt;=\S)(?=\s*$)))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-singlequote</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-doublequote</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-interpolated</string>
          </dict>
        </array>
      </dict>
      <key>string-singlequote</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.luau</string>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\')|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.luau</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>string-doublequote</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.luau</string>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.luau</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.luau</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.luau</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.luau</string>
        <key>match</key>
        <string>\\(x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|u\{[0-9A-Fa-f]+\}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
      </dict>
      <key>punctuation-comma</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.comma.luau</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <key>punctuation-semicolon</key>
      <dict>
        <key>name</key>
        <string>punctuation.terminator.statement.luau</string>
        <key>match</key>
        <string>;</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.luau</string>
            <key>begin</key>
            <string>--\[(=*)\[</string>
            <key>end</key>
            <string>\]\1\]</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-dash.luau</string>
            <key>begin</key>
            <string>--</string>
            <key>end</key>
            <string>\n</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>